### ISSUE TITLE
PaymentRequest uses double for the amount

### ISSUE THREAD

**Issue by jbackes** [sofort/sofortlib-java#4]
The PaymentRequest class expects a double as amount which is, in my opinion, highly dangerous and does not even reliably work in practice.

Doubles/Floats should never be used for currency values as explained here:
http://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

When doing the following request (using the provided example):

```
double amount = 1.03 - .42;
new PaymentInitialiser().initialiseSofortPayment(amount, "EUR", false, "foo");
```

you get an "IllegalStateException occured : Initialization errors: code:8014 / message:Invalid amount. / field: amount" because the actual amount that is sent to the server is 0.6100000000000001 and not 0.61 as expected.

I highly recommend to use BigDecimals.

**Comment by FxAlex** [comment]
"The right way to solve this problem is to use BigDecimal, int or long for **monetary _calculations_**."
i.e.
long amount = 103 - 42;
_and after all calculations_ amount / 100d -> Request

Usage of BigDecimal doesn't really solve the floating-point problem:
1.03-0.42 = 0.6100000000000001
new BigDecimal(1.03).subtract(new BigDecimal(0.42)) = 0.610000000000000042188474935755948536098003387451171875
